docker:
  - image: cimg/base:current
resource_class: small
steps:
  - setup-mise
  - run:
      name: Create test results directory
      command: mkdir -p test-results
  - run:
      name: Check
      command: bun run check
  - store_test_results:
      path: test-results
  - save-turbo-cache
