/**
 * CI release script — replicates changesets/action@v1 behavior.
 *
 * Two paths:
 * 1. Pending changesets → run `changeset version`, create/update a "Version Packages" PR
 * 2. No pending changesets → mint OIDC token, run `changeset publish`, push tags
 *
 * Uses the IO adapter (lib/ci-io.ts) for all side effects so the
 * orchestration logic is fully testable.
 */

import { filterPendingChangesets, shouldPublish } from './lib/changesets'
import { io } from './lib/ci-io'

const RELEASE_BRANCH = 'changeset-release/main'
const PR_TITLE = 'Version Packages'
const PR_BODY = 'This PR was auto-generated by the release workflow. Merging it will publish the new versions.'

export async function versionAndCreatePR(): Promise<number> {
  io.log('Pending changesets found. Creating version PR...')

  // Mint a GitHub App token for gh CLI (PR creation) and git push
  const ghToken = await io.mintGitHubToken()
  process.env.GH_TOKEN = ghToken

  await io.changesetVersion()
  await io.bunInstall()

  // Check for actual changes after versioning
  const diff = await io.gitDiff()
  const diffCached = await io.gitDiffCached()
  if (diff.exitCode === 0 && diffCached.exitCode === 0) {
    io.log('No changes after versioning, nothing to do.')
    return 0
  }

  // Configure git identity
  await io.gitConfig('user.name', 'circleci[bot]')
  await io.gitConfig('user.email', 'circleci[bot]@users.noreply.github.com')

  // Create/update branch and push
  await io.gitCheckout(RELEASE_BRANCH)
  await io.gitAdd()
  await io.gitCommit('ci(release): version packages')
  await io.gitPush('origin', RELEASE_BRANCH, true)

  // Create or update PR
  const prNumber = (await io.ghPrList(RELEASE_BRANCH)).trim()
  if (prNumber) {
    io.log(`Updated existing PR #${prNumber}`)
  } else {
    await io.ghPrCreate('main', RELEASE_BRANCH, PR_TITLE, PR_BODY)
    io.log('Created new Version Packages PR.')
  }

  return 0
}

export async function publish(): Promise<number> {
  io.log('No pending changesets. Publishing...')

  // Mint OIDC token for npm trusted publishing
  const oidcToken = (await io.mintOidcToken()).trim()
  process.env.NPM_ID_TOKEN = oidcToken

  await io.changesetPublish()
  await io.gitPushTags('origin', 'main')

  io.log('Published successfully.')
  return 0
}

export async function main(): Promise<number> {
  const files = await io.scanDir('.changeset')
  const pending = filterPendingChangesets(files)

  if (shouldPublish(pending)) {
    return publish()
  }

  io.log(`Found ${pending.length} pending changeset(s).`)
  return versionAndCreatePR()
}

if (import.meta.main) {
  const code = await main().catch((err) => {
    io.error(err.message)
    return 1
  })
  process.exit(code)
}
